name: Update Rules
on: 
  schedule:
    - cron: '30 18 * * *' # UTC+8，实际是北京时间凌晨02:30

  push:
    paths:
      - '.github/workflows/Update Rules.yaml'

  workflow_dispatch:

  repository_dispatch:
   type:
    - [Manual-Update]

jobs:
  update-rules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Update Rules
        continue-on-error: false
        run: |
          cd upstream
          rm -rf *
          wget https://raw.githubusercontent.com/neodevpro/neodevhost/master/smartdns.conf
          wget https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising_Classical.yaml
          wget https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-smartdns.conf
          wget https://raw.githubusercontent.com/Cats-Team/AdRules/main/smart-dns.conf
          cd ../rules

          update_time="$(TZ=UTC-8 date +'%Y-%m-%d %H:%M:%S')(GMT+8)"
          
          mkdir temp
          cat ../WhiteList.txt | sort | uniq > temp/WhiteList.txt
          cat ../BlackList.txt | sort | uniq > temp/BlackList.txt
          cat ../upstream/*.conf | sed '/^#/d' | sort | uniq > temp/smartdns.conf
          cat ../upstream/Advertising_Classical.yaml | sed '/^#/d' | sort | uniq > temp/clash.yaml
          cat temp/clash.yaml | sed "/  - DOMAIN.*,(.*)/d" > temp/clash_without_domain.yaml
          cat temp/smartdns.conf | sed -r "s/address \/(.*)\/#/\1/g" > temp/temp.txt
          cat temp/clash.yaml | grep -E "  - DOMAIN.*,.*" | sed -r "s/  - DOMAIN.*,(.*)/\1/g" >> temp/temp.txt
          cat temp/BlackList.txt >> temp/temp.txt
          cat temp/temp.txt | sort | uniq > temp/ad_domain_list.txt
          comm -2 -3 temp/ad_domain_list.txt temp/WhiteList.txt > ad_domain_list.txt

          cat ../title/smartdns_title.txt > smartdns.conf 
          echo "#" >> smartdns.conf
          echo "# Total count: $(wc -l < ad_domain_list.txt)" >> smartdns.conf
          echo "#" >> smartdns.conf
          echo "# Update: $update_time" >> smartdns.conf
          echo "#" >> smartdns.conf
          echo "#==========================================================================" >> smartdns.conf
          cat ad_domain_list.txt | awk '{print "address /%s/#",$0}' >> smartdns.conf
          
          cat ../title/clash_title.txt > advertising_classical.yaml
          echo "#" >> advertising_classical.yaml
          echo "# Total count: $(expr $(wc -l < ad_domain_list)+$(wc -l < temp/clash_without_domain.yaml))" >> advertising_classical.yaml
          echo "#" >> advertising_classical.yaml
          echo "# Update: $update_time" >> advertising_classical.yaml
          echo "#" >> advertising_classical.yaml
          echo "#==========================================================================" >> advertising_classical.yaml
          echo "payload:" >> advertising_classical.yaml
          cat ad_domain_list.txt | awk '{print "  - DOMAIN-SUFFIX,%s",$0}' >> advertising_classical.yaml
          cat temp/clash_without_domain.yaml >> advertising_classical.yaml

          cat ../title/loon_title.txt > loon.list
          echo "#" >> loon.list
          echo "# Total count: $(wc -l < temp/clash.yaml)" >> loon.list
          echo "#" >> loon.list
          echo "# Update: $update_time" >> loon.list
          echo "#" >> loon.list
          echo "#==========================================================================" >> loon.list
          cat ad_domain_list.txt | awk '{print "DOMAIN-SUFFIX,%s",$0}' >> loon.list
          
          rm -rf temp
          
      - name: Git push assets to Github
        run: |
          git init
          git config --local user.name "actions"
          git config --local user.email "action@github.com"  
          git add .
          git commit -m "Update at $(TZ=UTC-8 date +"%Y-%m-%d %H:%M")"
          git push -f -u origin main
      # - name: Git push assets to other repos
      #   continue-on-error: true
      #   run: |
      #     rm -rf .git/
      #     git init          
      #     git config --local user.name "hacamer"
      #     git config --local user.email "hcamer145@gmail.com"
      #     git remote add origin "https://cats-team:${{ secrets.GITLAB_TOKEN }}@gitlab.com/cats-team/adrules.git"
      #     git remote set-url --add origin "https://hacamer:${{ secrets.GITEA_TOKEN }}@gitea.com/Cats-Team/AdRules.git"
      #     git remote set-url --add origin "https://hacamer:${{ secrets.BITBUCKET_TOKEN }}@bitbucket.org/hacamer/adrules.git"
      #     git checkout --orphan clearhistory
      #     git add *.{conf,html,txt,json,srs,list} rules/* mod/*
      #     git commit -am "Update at $(TZ=UTC-8 date +"%Y-%m-%d %H:%M")"
      #     git branch -m main
      #     git push --force --set-upstream origin main
      # - name: Auto Built
      #   continue-on-error: true
      #   run: |
      #     curl -X POST "${{ secrets.CF_TOKEN }}"
