name: Update Rules
on: 
  schedule:
    - cron: '30 18 * * *' # UTC+8，实际是北京时间凌晨02:30

  push:
    paths:
      - '.github/workflows/Update Rules.yaml'

  workflow_dispatch:

  repository_dispatch:
   type:
    - [Manual-Update]

jobs:
  update-rules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Update Rules
        continue-on-error: false
        run: |
          cd upstream
          rm -rf *.conf
          wget https://raw.githubusercontent.com/neodevpro/neodevhost/master/smartdns.conf
          wget https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising_Classical.yaml
          wget https://anti-ad.net/anti-ad-for-smartdns.conf
          wget https://adrules.top/smart-dns.conf
          cd ../rules

          update_time="$(TZ=UTC-8 date +'%Y-%m-%d %H:%M:%S')(GMT+8)"
          
          mkdir temp
          cat ../upstream/*.conf | sed '/^#/d' | sort | uniq > temp/smartdns.conf
          cat ../upstream/Advertising_Classical.yaml | sed '/^#/d' | sort | uniq > temp/clash1.yaml

          total_count="$(wc -l < temp/smartdns.conf)"

          cat temp/smartdns.conf | sed -r "s/address \/(.*)\/#/\1/g" > ad_domain_list.txt
          
          cat ../title/smartdns_title.txt > smartdns.conf 
          echo "#" >> smartdns.conf
          echo "# Total count: $total_count" >> smartdns.conf
          echo "#" >> smartdns.conf
          echo "# Update: $update_time" >> smartdns.conf
          echo "#" >> smartdns.conf
          echo "#==========================================================================" >> smartdns.conf
          cat temp/smartdns.conf >> smartdns.conf 

          cat ../title/clash_title.txt > temp/clash2.yaml
          echo "#" >> temp/clash2.yaml
          echo "# Total count: $[ $total_count+$(wc -l < temp/another_clash.yaml)-1 ]" >> temp/clash2.yaml
          echo "#" >> temp/clash2.yaml
          echo "# Update: $update_time" >> temp/clash2.yaml
          echo "#" >> temp/clash2.yaml
          echo "#==========================================================================" >> temp/clash2.yaml
          echo "payload:" >> temp/clash2.yaml
          cat temp/smartdns.conf | sed -r "s/address \/(.*)\/#/  - DOMAIN-SUFFIX,\1/g" >> temp/clash2.yaml
          cat temp/clash*.yaml | sort | uniq > clash.yaml

          rm -rf temp
          
      - name: Git push assets to Github
        run: |
          git init
          git config --local user.name "actions"
          git config --local user.email "action@github.com"  
          git add .
          git commit -m "Update at $(TZ=UTC-8 date +"%Y-%m-%d %H:%M")"
          git push -f -u origin main
      # - name: Git push assets to other repos
      #   continue-on-error: true
      #   run: |
      #     rm -rf .git/
      #     git init          
      #     git config --local user.name "hacamer"
      #     git config --local user.email "hcamer145@gmail.com"
      #     git remote add origin "https://cats-team:${{ secrets.GITLAB_TOKEN }}@gitlab.com/cats-team/adrules.git"
      #     git remote set-url --add origin "https://hacamer:${{ secrets.GITEA_TOKEN }}@gitea.com/Cats-Team/AdRules.git"
      #     git remote set-url --add origin "https://hacamer:${{ secrets.BITBUCKET_TOKEN }}@bitbucket.org/hacamer/adrules.git"
      #     git checkout --orphan clearhistory
      #     git add *.{conf,html,txt,json,srs,list} rules/* mod/*
      #     git commit -am "Update at $(TZ=UTC-8 date +"%Y-%m-%d %H:%M")"
      #     git branch -m main
      #     git push --force --set-upstream origin main
      # - name: Auto Built
      #   continue-on-error: true
      #   run: |
      #     curl -X POST "${{ secrets.CF_TOKEN }}"
