name: Update Rules
on: 
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

  repository_dispatch:
   type:
    - [Manual-Update]

jobs:
  update-rules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Update Rules
        continue-on-error: false
        run: |
          mkdir upstream
          mkdir rules
          ls .
          cd upstream
          wget https://raw.githubusercontent.com/neodevpro/neodevhost/master/smartdns.conf
          wget https://anti-ad.net/anti-ad-for-smartdns.conf
          wget https://adrules.top/smart-dns.conf
          ls .
          cd ../
          ls .
          cat upstream/*.conf | sed -e '/^#/d' | sort | uniq > rules/smartdns.conf
          ls ./rules
          
      - name: Git push assets to Github
        run: |
          git init
          git config --local user.name "actions"
          git config --local user.email "action@github.com"
          git checkout --orphan main
          git rm -rf .github
          git rm -rf script
          git rm -rf *.md      
          git add upstream/*.{conf,txt,list,html,json,srs} upstream/*
          git add rules/*.{conf,txt,list,html,json,srs} rules/*
          git commit -m "Update at $(TZ=UTC-8 date +"%Y-%m-%d %H:%M")"
          git push -f -u origin main
      # - name: Git push assets to other repos
      #   continue-on-error: true
      #   run: |
      #     rm -rf .git/
      #     git init          
      #     git config --local user.name "hacamer"
      #     git config --local user.email "hcamer145@gmail.com"
      #     git remote add origin "https://cats-team:${{ secrets.GITLAB_TOKEN }}@gitlab.com/cats-team/adrules.git"
      #     git remote set-url --add origin "https://hacamer:${{ secrets.GITEA_TOKEN }}@gitea.com/Cats-Team/AdRules.git"
      #     git remote set-url --add origin "https://hacamer:${{ secrets.BITBUCKET_TOKEN }}@bitbucket.org/hacamer/adrules.git"
      #     git checkout --orphan clearhistory
      #     git add *.{conf,html,txt,json,srs,list} rules/* mod/*
      #     git commit -am "Update at $(TZ=UTC-8 date +"%Y-%m-%d %H:%M")"
      #     git branch -m main
      #     git push --force --set-upstream origin main
      # - name: Auto Built
      #   continue-on-error: true
      #   run: |
      #     curl -X POST "${{ secrets.CF_TOKEN }}"
